### ISSUE TITLE
Illegal characters for file and folder names (/ and :) in metadata titles

### ISSUE THREAD

**Issue by ZetsApocNow** [potatoeggy/mandown#77]
**What broke?**

- [x] Downloader
- [ ] Processor
- [x] Converter
- [ ] Other

**Mandown version**
Output of `mandown --version`: 1.70

**Describe the bug**

The script isn't removing illegal characters such as : and / from metadata titles, therefore creating invalid file and folder names which then makes the whole thing error out.

**Steps to reproduce**
If the downloader broke, please include a URL that breaks it.

Downloading any comic with : or / in the name, for example

https://readcomiconline.li/Comic/Venom-Sign-of-the-Boss
or
https://readcomiconline.li/Comic/Venom-Deadpool-What-If

**Additional context**

**Comment by potatoeggy** [comment]
Thank you for reporting this issue! Please try Mandown 1.8.1, which contains a fix for this bug.

**Comment by ZetsApocNow** [comment]
The update you did, now makes this happen

AttributeError: 'Metadata' object has no attribute 'title_slug'

Test Url - https://readcomiconline.li/Comic/Venom-Modern-Era-Epic-Collection

**Comment by potatoeggy** [comment]
Oops — that's what I get for not exhaustively testing. Thanks for catching that! I've run through the full flows with your comic links and they should now all work with v1.8.2.

**Comment by ZetsApocNow** [comment]
So I'm on v1.8.2 now and the same error exists. I've noticed that in Base.py that comparing the first part with the chapter part, as chapter part has a working slug, that there is a line missing for returning a value for title_slug

![image](https://github.com/potatoeggy/mandown/assets/93975191/74d4b83d-338d-4fd6-bb03-ab4c006e0fb2)

I added the line (```            "title_slug": self.title_slug,```) and title_slug now populates correctly in metadata and is slugified 
![image](https://github.com/potatoeggy/mandown/assets/93975191/c57080d2-071b-4be0-960a-4e1c63e8e179)

but the script is returning this error once run, saying that Metadata doesn't contain the title_slug field when it clearly does

```PS V:\Jellyfin\All Files\Graphic Novels> mandown get -c cbz -b -r https://readcomiconline.li/Comic/Venom-Modern-Era-Epic-Collection
Searching sources for https://readcomiconline.li/Comic/Venom-Modern-Era-Epic-Collection
Found comic "Venom Modern Era Epic Collection" from source ReadComicOnline
Downloading 10 chapter(s)...
The Savage Six (Part 5)  [####################################]  100%
Successfully downloaded 10 chapter(s) to V:\Jellyfin\All Files\Graphic Novels\venom-modern-era-epic-collection.
Venom Modern Era Epic Collection - Agent Venom (Part 1)  [###---------------------------------]   10%
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\theda\AppData\Local\Programs\Python\Python310\lib\site-packages\mandown\cli.py:450 in   │
│ get                                                                                              │
│                                                                                                  │
│   447 │                                                                                          │
│   448 │   # convert                                                                              │
│   449 │   if convert_to != ConvertFormats.NONE:                                                  │
│ ❱ 450 │   │   cli_convert(                                                                       │
│   451 │   │   │   dest / comic.metadata.title_slug,                                              │
│   452 │   │   │   convert_to,                                                                    │
│   453 │   │   │   dest,                                                                          │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              comic = <mandown.comic.BaseComic object at 0x000001870FDD3940>                  │ │
│ │         convert_to = <ConvertFormats.CBZ: 'cbz'>                                             │ │
│ │               dest = WindowsPath('V:/Jellyfin/All Files/Graphic Novels')                     │ │
│ │                end = None                                                                    │ │
│ │        end_chapter = 10                                                                      │ │
│ │   full_dest_folder = WindowsPath('V:/Jellyfin/All Files/Graphic                              │ │
│ │                      Novels/venom-modern-era-epic-collection')                               │ │
│ │         maxthreads = 4                                                                       │ │
│ │ processing_options = []                                                                      │ │
│ │           progress = <click._termui_impl.ProgressBar object at 0x000001870FECE950>           │ │
│ │       remove_after = True                                                                    │ │
│ │       size_profile = None                                                                    │ │
│ │  split_by_chapters = True                                                                    │ │
│ │              start = None                                                                    │ │
│ │      start_chapter = 0                                                                       │ │
│ │        target_size = None                                                                    │ │
│ │              title = 'The Savage Six (Part 5)'                                               │ │
│ │                url = 'https://readcomiconline.li/Comic/Venom-Modern-Era-Epic-Collection'     │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\theda\AppData\Local\Programs\Python\Python310\lib\site-packages\mandown\cli.py:177 in   │
│ cli_convert                                                                                      │
│                                                                                                  │
│   174 │   │   │   length=len_first_conv,                                                         │
│   175 │   │   │   label=first_convert_message,                                                   │
│   176 │   │   ) as progress:                                                                     │
│ ❱ 177 │   │   │   for res in progress:                                                           │
│   178 │   │   │   │   if isinstance(res, int):                                                   │
│   179 │   │   │   │   │   len_second_conv = res                                                  │
│   180 │   │   │   │   │   break                                                                  │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │            comic_path = WindowsPath('V:/Jellyfin/All Files/Graphic                           │ │
│ │                         Novels/venom-modern-era-epic-collection')                            │ │
│ │           dest_folder = WindowsPath('V:/Jellyfin/All Files/Graphic Novels')                  │ │
│ │ first_convert_message = 'Packing cbz(s)'                                                     │ │
│ │  is_single_conversion = True                                                                 │ │
│ │              iterator = <generator object convert_progress at 0x000001870FEDA0A0>            │ │
│ │        len_first_conv = 10                                                                   │ │
│ │       len_second_conv = -1                                                                   │ │
│ │              progress = <click._termui_impl.ProgressBar object at 0x000001870FEF7430>        │ │
│ │          remove_after = True                                                                 │ │
│ │                   res = 'Venom Modern Era Epic Collection - Agent Venom (Part 1)'            │ │
│ │     split_by_chapters = True                                                                 │ │
│ │         target_format = <ConvertFormats.CBZ: 'cbz'>                                          │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ C:\Users\theda\AppData\Local\Programs\Python\Python310\lib\site-packages\click\_termui_impl.py:3 │
│ 44 in generator                                                                                  │
│                                                                                                  │
│ C:\Users\theda\AppData\Local\Programs\Python\Python310\lib\site-packages\mandown\api.py:146 in   │
│ convert_progress                                                                                 │
│                                                                                                  │
│   143 │   │   │   │   yield comicomic.metadata.title                                             │
│   144 │   │   │   │                                                                              │
│   145 │   │   │   │   # do not overwrite existing cache                                          │
│ ❱ 146 │   │   │   │   if f"{comicomic.metadata.title_slug}.{to.value}" in existing_filenames:    │
│   147 │   │   │   │   │   continue                                                               │
│   148 │   │   │   │   for _ in convert_one(comicomic, comic_path, to, dest_folder):              │
│   149 │   │   │   │   │   ...                                                                    │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │              comic = <mandown.comic.BaseComic object at 0x000001870FEF73A0>                  │ │
│ │         comic_path = WindowsPath('V:/Jellyfin/All Files/Graphic                              │ │
│ │                      Novels/venom-modern-era-epic-collection')                               │ │
│ │          comicomic = Comic(                                                                  │ │
│ │                      │   metadata=Metadata(                                                  │ │
│ │                      │   │   title='Venom Modern Era Epic Collection - Agent Venom (Part     │ │
│ │                      1)',                                                                    │ │
│ │                      │   │   authors=['Christopher Yost'],                                   │ │
│ │                      │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum        │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   genres=['Action', 'Adventure', 'Superhero'],                    │ │
│ │                      │   │   cover_path_rel='cover.jpg',                                     │ │
│ │                      │   │   extra_metadata={}                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   chapters=[                                                          │ │
│ │                      │   │   Chapter(                                                        │ │
│ │                      │   │   │   title='Agent Venom (Part 1)',                               │ │
│ │                      │   │   │   slug='agent-venom-part-1'                                   │ │
│ │                      │   │   )                                                               │ │
│ │                      │   ]                                                                   │ │
│ │                      )                                                                       │ │
│ │     comicon_comics = [                                                                       │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - Agent Venom (Part │ │
│ │                      1)',                                                                    │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='Agent Venom (Part 1)',                           │ │
│ │                      │   │   │   │   slug='agent-venom-part-1'                               │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - Agent Venom (Part │ │
│ │                      2)',                                                                    │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='Agent Venom (Part 2)',                           │ │
│ │                      │   │   │   │   slug='agent-venom-part-2'                               │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - Agent Venom (Part │ │
│ │                      3)',                                                                    │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='Agent Venom (Part 3)',                           │ │
│ │                      │   │   │   │   slug='agent-venom-part-3'                               │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - Agent Venom (Part │ │
│ │                      4)',                                                                    │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='Agent Venom (Part 4)',                           │ │
│ │                      │   │   │   │   slug='agent-venom-part-4'                               │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - Agent Venom (Part │ │
│ │                      5)',                                                                    │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='Agent Venom (Part 5)',                           │ │
│ │                      │   │   │   │   slug='agent-venom-part-5'                               │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - The Savage Six    │ │
│ │                      (Part 1)',                                                              │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='The Savage Six (Part 1)',                        │ │
│ │                      │   │   │   │   slug='the-savage-six-part-1'                            │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - The Savage Six    │ │
│ │                      (Part 2)',                                                              │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='The Savage Six (Part 2)',                        │ │
│ │                      │   │   │   │   slug='the-savage-six-part-2'                            │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - The Savage Six    │ │
│ │                      (Part 3)',                                                              │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='The Savage Six (Part 3)',                        │ │
│ │                      │   │   │   │   slug='the-savage-six-part-3'                            │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - The Savage Six    │ │
│ │                      (Part 4)',                                                              │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='The Savage Six (Part 4)',                        │ │
│ │                      │   │   │   │   slug='the-savage-six-part-4'                            │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   ),                                                                  │ │
│ │                      │   Comic(                                                              │ │
│ │                      │   │   metadata=Metadata(                                              │ │
│ │                      │   │   │   title='Venom Modern Era Epic Collection - The Savage Six    │ │
│ │                      (Part 5)',                                                              │ │
│ │                      │   │   │   authors=['Christopher Yost'],                               │ │
│ │                      │   │   │   description='Collects Venom (2011) #17-35, 27.1; Minimum    │ │
│ │                      Carnage: Alpha (2012) #1; Scarlet Sp'+706,                              │ │
│ │                      │   │   │   genres=['Action', 'Adventure', 'Superhero'],                │ │
│ │                      │   │   │   cover_path_rel='cover.jpg',                                 │ │
│ │                      │   │   │   extra_metadata={}                                           │ │
│ │                      │   │   ),                                                              │ │
│ │                      │   │   chapters=[                                                      │ │
│ │                      │   │   │   Chapter(                                                    │ │
│ │                      │   │   │   │   title='The Savage Six (Part 5)',                        │ │
│ │                      │   │   │   │   slug='the-savage-six-part-5'                            │ │
│ │                      │   │   │   )                                                           │ │
│ │                      │   │   ]                                                               │ │
│ │                      │   )                                                                   │ │
│ │                      ]                                                                       │ │
│ │              cover = 'cover.jpg'                                                             │ │
│ │        dest_folder = WindowsPath('V:/Jellyfin/All Files/Graphic Novels')                     │ │
│ │ existing_filenames = {'penis.bat', 'how to download.txt'}                                    │ │
│ │               item = WindowsPath('V:/Jellyfin/All Files/Graphic                              │ │
│ │                      Novels/venom-modern-era-epic-collection/cover.jpg')                     │ │
│ │       remove_after = True                                                                    │ │
│ │  split_by_chapters = True                                                                    │ │
│ │                 to = <ConvertFormats.CBZ: 'cbz'>                                             │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Metadata' object has no attribute 'title_slug'```

upon looking at it, the script isn't seeing the title_slug field at all, even though it's set

![image](https://github.com/potatoeggy/mandown/assets/93975191/bfc705fc-5225-4942-8632-d865ab5ece45)

**Comment by ZetsApocNow** [comment]
That last image is - 
![image](https://github.com/potatoeggy/mandown/assets/93975191/15651226-3ff3-454c-a143-10e13fa3dbd2)
